name: CI

on:
    pull_request:
        branches: [master]
        paths:
            - "packages/**"
            - "package.json"
            - "yarn.lock"
            - ".github/**"
    push:
        branches: [master]
        paths:
            - "packages/**"
            - "package.json"
            - "yarn.lock"
            - ".github/**"

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - run: corepack enable

            - run: corepack yarn install --immutable

            - run: corepack yarn build

            - run: corepack yarn type-check

            - run: corepack yarn workspace @bitsocial/spam-blocker-server test

            - run: corepack yarn workspace @bitsocial/spam-blocker-challenge test

            - run: corepack yarn format:check
